{% set version = "0.0.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gap.datasets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gap.datasets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gap.datasets/gap.datasets_{{ version }}.tar.gz
  sha256: 1e14b06fac203016555ddca323225ccf18d784609dbf9bdfff423e6dccd297cb

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gap.datasets')"           # [not win]
    - "\"%R%\" -e \"library('gap.datasets')\""  # [win]

about:
  home: https://jinghuazhao.github.io/R/
  license: GPL-2.0-or-later
  summary: Datasets associated with the 'gap' package. Currently, it includes an example data for regional association plot (CDKN), an example data for a genomewide association meta-analysis (OPG), data in studies of Parkinson's diease (PD), ALHD2 markers and alcoholism (aldh2), APOE/APOC1 markers and Schizophrenia (apoeapoc),
    cystic fibrosis (cf), a Olink/INF panel (inf1), Manhattan plots with (hr1420, mhtdata) and without (w4) gene annotations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
